# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6709aaa1bf80c3fc85de0dc5f163d36ac5087fef118a6f406756595759c7e9441fd5ab0bfb89aaee8d1da69b6e60aafee4b6ead2d0ea2f643f961a751a8f5048

test:
  secret_key_base: ded6996c4b18cd581413800b026d9c7c96ff2e6a6ff255fd8f4437bcd749eeff632e5590c9f4a80a1474c8ef3cd4cde89b2c4e4c45615cbbe1ccbd646c8a5592

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
